version: '3' # docker-compose version

services: # list of services
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    volumes:
      - /home/v0026/Desktop/zadanie/quest:/opt/bitnami/spark/quest

  spark-worker:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    restart: on-failure
    # depends_on:
    #   - "spark"
  db:
    container_name: 'mysql'
    image: mysql
    environment:
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 9090:9090 #HOST:CONTAINER
    expose:
    - "3306"
    volumes:
    - ./database:/docker-entrypoint-initdb.d/:ro
